# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

BPF_TARGETS := \
    pfc_decap_tc \
    pfc_encap_tc \
    pfc_tag_rx_tc

LIBBPF_DIR = ../../libbpf/src/
COMMON_DIR = ../../common/
HEADER_DIR = ../../headers/

include $(COMMON_DIR)/common.mk
