#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# TrueIngress adhoc Linux installation script.

OPT=/opt/acnodal
EPIC_REPO=https://github.com/epic-gateway
MGR_VER=v0.56.0
CTL_VER=v0.11.1
TI_VER=v0.22.4
GET="wget --no-verbose"

# We need to have an account name so we can set up the configuration.
ACCOUNT=${1:-}
if [ "X$ACCOUNT" = "X" ] ; then
    echo "An EPIC account name must be provided"
    exit 1
fi

# Create directories
mkdir -p /etc/kubernetes $OPT/bin $OPT/etc

# Add our tools to the PATH, and tell kubectl where to find its config
cat > /etc/profile.d/acnodal.sh <<HERE
export PATH="\$PATH:$OPT/bin"
export KUBECONFIG=/etc/kubernetes/admin.conf
HERE

# Download epicctl
eval $GET --output-document=$OPT/bin/epicctl ${EPIC_REPO}/epicctl/releases/download/${CTL_VER}/epicctl
chmod +x $OPT/bin/epicctl

# Download true ingress binaries
eval $GET --output-document=- ${EPIC_REPO}/true-ingress/releases/download/${TI_VER}/true-ingress.tar.bz2 | tar xjf - -C $OPT

# Download and start systemd service file for the GUE ping program
eval $GET --output-document=/usr/lib/systemd/system/gue_ping_svc_auto.service ${EPIC_REPO}/true-ingress/releases/download/${TI_VER}/gue_ping_svc_auto.service
systemctl enable --now gue_ping_svc_auto

# Download the manager
eval $GET --output-document=$OPT/bin/manager ${EPIC_REPO}/resource-model/releases/download/${MGR_VER}/manager
chmod +x $OPT/bin/manager
cat > $OPT/etc/manager.yaml <<HERE
account-name: ${ACCOUNT}
HERE

# Download and start systemd service and path files for the manager
for UNIT in manager.service manager-restart.service manager-restart.path ; do
    eval $GET --output-document=/usr/lib/systemd/system/${UNIT} ${EPIC_REPO}/resource-model/releases/download/${MGR_VER}/${UNIT}
    systemctl enable --now $UNIT
done

# The user needs to do this:
echo
echo \*\*\* Installation almost complete
echo
echo \*\*\* Please upload a kubectl config file to /etc/kubernetes/admin.conf
