#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# TrueIngress adhoc Linux installation script.

OPT=/opt/acnodal
EPIC_GITLAB=https://gitlab.com/api/v4/projects/acnodal%2Fepic%2F
MGR_VER=v0.54.1
CTL_VER=v0.9.0
TI_VER=v0.18.1

# We need to download files from private Gitlab repos so we need an
# access token.
TOKEN=${1:-}
if [ "X$TOKEN" = "X" ] ; then
    echo "A Gitlab access token must be provided"
    exit 1
fi

# Create directories
mkdir -p /etc/kubernetes $OPT/bin $OPT/etc

# Add our tools to the PATH, and tell kubectl where to find its config
cat > /etc/profile.d/acnodal.sh <<HERE
export PATH="\$PATH:$OPT/bin"
export KUBECONFIG=/etc/kubernetes/admin.conf
HERE

# Download epicctl
wget --no-verbose --header="PRIVATE-TOKEN: ${TOKEN}" --output-document=$OPT/bin/epicctl ${EPIC_GITLAB}epicctl/packages/generic/epicctl/${CTL_VER}/epicctl
chmod +x $OPT/bin/epicctl

# Download true ingress binaries
wget --no-verbose --header="PRIVATE-TOKEN: ${TOKEN}" --output-document=- ${EPIC_GITLAB}true-ingress/packages/generic/true-ingress/${TI_VER}/true-ingress.tar.bz2 | tar xjf - -C $OPT

# Download and start systemd service file for the GUE ping program
wget --no-verbose --header="PRIVATE-TOKEN: ${TOKEN}" --output-document=/usr/lib/systemd/system/gue_ping_svc_auto.service ${EPIC_GITLAB}true-ingress/packages/generic/true-ingress/${TI_VER}/gue_ping_svc_auto.service
systemctl enable --now gue_ping_svc_auto

# Download the manager
wget --no-verbose --header="PRIVATE-TOKEN: ${TOKEN}" --output-document=$OPT/bin/manager ${EPIC_GITLAB}resource-model/packages/generic/manifest-package/${MGR_VER}/manager
chmod +x $OPT/bin/manager
cat > $OPT/etc/manager.yaml <<HERE
account-name: REPLACE_THIS_WITH_YOUR_ACCOUNT_NAME
HERE

# Download and start systemd service and path files for the manager
for UNIT in manager.service manager-restart.service manager-restart.path ; do
    wget --no-verbose --header="PRIVATE-TOKEN: ${TOKEN}" --output-document=/usr/lib/systemd/system/${UNIT} ${EPIC_GITLAB}resource-model/packages/generic/manifest-package/${MGR_VER}/${UNIT}
    systemctl enable --now $UNIT
done

# The user needs to do this:
echo
echo \*\*\* Installation almost complete
echo
echo \*\*\* Please edit /opt/acnodal/etc/manager.yaml to ensure that it matches your setup
echo
echo \*\*\* Please upload a kubectl config file to /etc/kubernetes/admin.conf,
echo \*\*\* then run "source /etc/profile.d/acnodal.sh" to set up your environment
